title: osci-dev
description: Programs Dedicated to Families Involved with Developmental Disorders.
theme: jekyll-theme-midnight
exclude:
  - Dockerfile
  - docker-compose.yml
  - README.md
  - .git
  - .gitignore
  - .dockerignore
  - Gemfile
  - Gemfile.lock
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
repository: osci-dev/osci-dev.github.io