version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: jekyll serve --force_polling
    volumes:
      - ./:/srv/jekyll
      - bundle_data:/usr/local/bundle
    ports:
      - 4000:4000
volumes:
  bundle_data:
